const mockMenuData = {
  name: "Chhotu Di Hatti",
  cuisines: ["Beverages", "Sweets", "Fast Food", "Burgers", "Snacks", "Desserts", "Chinese", "South Indian"],
  avgRating: 4.2,
  deliveryTime: 35,
  costForTwo: "₹250 for two",
  menu: [
    {
      category: "Burgers",
      items: [
        { id: 1, name: "Veg Burger", price: 80, description: "Crispy veg patty with fresh veggies and special sauce", isVeg: true },
        { id: 2, name: "Chicken Burger", price: 120, description: "Juicy chicken patty with mayo and lettuce", isVeg: false },
        { id: 3, name: "Double Patty Burger", price: 150, description: "Double the fun with two juicy patties", isVeg: false },
        { id: 4, name: "Paneer Burger", price: 110, description: "Grilled paneer patty with mint chutney", isVeg: true },
        { id: 5, name: "Mushroom Burger", price: 100, description: "Sautéed mushrooms with cheese and veggies", isVeg: true },
        { id: 6, name: "Spicy Chicken Burger", price: 130, description: "Extra spicy chicken patty with jalapeños", isVeg: false },
        { id: 7, name: "Cheese Burst Burger", price: 160, description: "Loaded with molten cheese inside and out", isVeg: true },
        { id: 8, name: "BBQ Chicken Burger", price: 140, description: "Smoky BBQ chicken with caramelized onions", isVeg: false },
      ],
    },
    {
      category: "Beverages",
      items: [
        { id: 9, name: "Cold Coffee", price: 80, description: "Chilled coffee blended with ice cream", isVeg: true },
        { id: 10, name: "Mango Shake", price: 70, description: "Fresh Alphonso mango blended to perfection", isVeg: true },
        { id: 11, name: "Masala Chai", price: 30, description: "Hot spiced Indian tea with ginger", isVeg: true },
        { id: 12, name: "Strawberry Smoothie", price: 90, description: "Fresh strawberries blended with yogurt", isVeg: true },
        { id: 13, name: "Lassi", price: 50, description: "Thick creamy yogurt drink, sweet or salty", isVeg: true },
        { id: 14, name: "Lemon Soda", price: 40, description: "Fresh lime with fizzy soda and mint", isVeg: true },
        { id: 15, name: "Hot Chocolate", price: 90, description: "Rich creamy hot chocolate with marshmallows", isVeg: true },
        { id: 16, name: "Banana Shake", price: 65, description: "Thick banana shake with a hint of cardamom", isVeg: true },
        { id: 17, name: "Watermelon Juice", price: 55, description: "Fresh chilled watermelon juice with black salt", isVeg: true },
        { id: 18, name: "Oreo Shake", price: 100, description: "Crushed Oreos blended with vanilla ice cream", isVeg: true },
      ],
    },
    {
      category: "Sweets",
      items: [
        { id: 19, name: "Gulab Jamun", price: 40, description: "Soft fried dumplings soaked in rose sugar syrup", isVeg: true },
        { id: 20, name: "Jalebi", price: 35, description: "Crispy spiral sweets soaked in saffron syrup", isVeg: true },
        { id: 21, name: "Rasgulla", price: 45, description: "Soft spongy cottage cheese balls in light syrup", isVeg: true },
        { id: 22, name: "Halwa", price: 50, description: "Semolina cooked with ghee, sugar and dry fruits", isVeg: true },
        { id: 23, name: "Kheer", price: 55, description: "Creamy rice pudding with cardamom and nuts", isVeg: true },
        { id: 24, name: "Barfi", price: 60, description: "Milk fudge with pistachio and silver leaf", isVeg: true },
        { id: 25, name: "Ladoo", price: 30, description: "Besan ladoos made with pure ghee", isVeg: true },
        { id: 26, name: "Rabri", price: 65, description: "Thickened sweetened milk with saffron and nuts", isVeg: true },
      ],
    },
    {
      category: "Fast Food",
      items: [
        { id: 27, name: "Samosa", price: 20, description: "Crispy pastry filled with spiced potatoes and peas", isVeg: true },
        { id: 28, name: "Aloo Tikki", price: 30, description: "Spiced potato patty served with green chutney", isVeg: true },
        { id: 29, name: "Chole Bhature", price: 80, description: "Fluffy bhature with spicy tangy chole", isVeg: true },
        { id: 30, name: "Pav Bhaji", price: 70, description: "Spiced mashed veggies with buttered pav", isVeg: true },
        { id: 31, name: "Vada Pav", price: 25, description: "Mumbai's favourite street burger with chutney", isVeg: true },
        { id: 32, name: "Bread Pakora", price: 40, description: "Bread stuffed with potato, dipped in batter and fried", isVeg: true },
        { id: 33, name: "Egg Roll", price: 60, description: "Egg wrapped in paratha with onions and sauce", isVeg: false },
        { id: 34, name: "Chicken Roll", price: 90, description: "Grilled chicken wrapped in flaky paratha", isVeg: false },
      ],
    },
    {
      category: "Snacks",
      items: [
        { id: 35, name: "French Fries", price: 60, description: "Golden crispy fries with seasoning and ketchup", isVeg: true },
        { id: 36, name: "Pani Puri", price: 40, description: "Crispy puris filled with tangy spiced water", isVeg: true },
        { id: 37, name: "Bhel Puri", price: 45, description: "Puffed rice with chutneys and veggies", isVeg: true },
        { id: 38, name: "Nachos", price: 70, description: "Crunchy nachos with salsa and cheese dip", isVeg: true },
        { id: 39, name: "Onion Rings", price: 55, description: "Crispy battered onion rings with dipping sauce", isVeg: true },
        { id: 40, name: "Corn Chaat", price: 50, description: "Spiced sweet corn with lemon and masala", isVeg: true },
        { id: 41, name: "Chicken Wings", price: 150, description: "Crispy fried wings tossed in spicy sauce", isVeg: false },
        { id: 42, name: "Paneer Tikka", price: 130, description: "Marinated paneer grilled in tandoor with spices", isVeg: true },
      ],
    },
    {
      category: "Desserts",
      items: [
        { id: 43, name: "Chocolate Brownie", price: 90, description: "Warm fudgy brownie with vanilla ice cream", isVeg: true },
        { id: 44, name: "Ice Cream Sundae", price: 100, description: "Three scoops with hot fudge and whipped cream", isVeg: true },
        { id: 45, name: "Waffle", price: 110, description: "Crispy waffle with maple syrup and fresh fruits", isVeg: true },
        { id: 46, name: "Cheesecake", price: 120, description: "New York style baked cheesecake with berry compote", isVeg: true },
        { id: 47, name: "Kulfi", price: 50, description: "Traditional Indian ice cream with pistachio", isVeg: true },
        { id: 48, name: "Mango Sorbet", price: 80, description: "Refreshing mango sorbet with a tangy twist", isVeg: true },
        { id: 49, name: "Chocolate Mousse", price: 95, description: "Light airy chocolate mousse with cocoa dusting", isVeg: true },
        { id: 50, name: "Fruit Custard", price: 70, description: "Creamy vanilla custard loaded with fresh fruits", isVeg: true },
      ],
    },
    {
      category: "Chinese",
      items: [
        { id: 51, name: "Veg Fried Rice", price: 90, description: "Wok tossed rice with veggies and soy sauce", isVeg: true },
        { id: 52, name: "Chicken Fried Rice", price: 120, description: "Classic fried rice with tender chicken pieces", isVeg: false },
        { id: 53, name: "Veg Noodles", price: 85, description: "Hakka noodles stir fried with veggies", isVeg: true },
        { id: 54, name: "Chicken Noodles", price: 115, description: "Hakka noodles with juicy chicken and sauces", isVeg: false },
        { id: 55, name: "Veg Manchurian", price: 100, description: "Fried veggie balls in spicy Manchurian sauce", isVeg: true },
        { id: 56, name: "Chilli Paneer", price: 130, description: "Crispy paneer tossed in spicy chilli sauce", isVeg: true },
        { id: 57, name: "Spring Rolls", price: 80, description: "Crispy rolls stuffed with veggies and noodles", isVeg: true },
        { id: 58, name: "Chicken Momos", price: 110, description: "Steamed dumplings filled with spiced chicken", isVeg: false },
        { id: 59, name: "Veg Momos", price: 90, description: "Steamed dumplings with spiced veggie filling", isVeg: true },
      ],
    },
    {
      category: "South Indian",
      items: [
        { id: 60, name: "Masala Dosa", price: 80, description: "Crispy dosa stuffed with spiced potato filling", isVeg: true },
        { id: 61, name: "Plain Dosa", price: 60, description: "Thin crispy rice crepe with sambar and chutney", isVeg: true },
        { id: 62, name: "Idli Sambar", price: 50, description: "Soft steamed rice cakes with sambar and chutney", isVeg: true },
        { id: 63, name: "Medu Vada", price: 55, description: "Crispy lentil donuts with coconut chutney", isVeg: true },
        { id: 64, name: "Uttapam", price: 70, description: "Thick rice pancake topped with onions and tomatoes", isVeg: true },
        { id: 65, name: "Rava Dosa", price: 75, description: "Crispy semolina dosa with cashews and pepper", isVeg: true },
        { id: 66, name: "Pongal", price: 65, description: "Comforting rice and lentil dish with ghee and pepper", isVeg: true },
        { id: 67, name: "Paniyaram", price: 60, description: "Soft fluffy rice balls served with spicy chutney", isVeg: true },
      ],
    },
  ],
};

export default mockMenuData;